# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='genre',
            field=models.CharField(default=datetime.datetime(2017, 6, 29, 18, 40, 48, 388687, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='rating',
            field=models.BooleanField(default=False),
        ),
    ]
